### ISSUE TITLE
when i try

### ISSUE THREAD

**Issue by rootSectornet** [ahoefling/TabStrip#27]
Error CS0029: Cannot implicitly convert type 'System.Tuple<Xamarin.Forms.View, object>' to '(Xamarin.Forms.View View, object BindingContext)' (CS0029) (Tootanium)

**Comment by yunusefendi52** [comment]
You use either like this:
`new Tuple<View, object>(new ContentView(), new { Title = "1" }).ToValueTuple()`
or:
`(new ContentView(), new { Title = "1" })`

**Comment by SkyeHoefling** [comment]
Closing questions since it appears to be answered. If you have another question don't hesitate to open another question
